import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F7FAFC' },
  authContainer: { flex: 1, backgroundColor: '#1A365D', justifyContent: 'center', padding: 20 },
  authCard: { backgroundColor: '#FFFFFF', borderRadius: 24, padding: 30, elevation: 10 },
  authTitle: { fontSize: 36, fontWeight: 'bold', color: '#1A365D', textAlign: 'center', marginBottom: 8 },
  authSubtitle: { fontSize: 16, color: '#718096', textAlign: 'center', marginBottom: 35 },
  input: { backgroundColor: '#F7FAFC', borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 12, padding: 16, marginBottom: 16, fontSize: 16, color: '#2D3748' },
  primaryButton: { backgroundColor: '#3182CE', padding: 18, borderRadius: 12, alignItems: 'center', marginTop: 10 },
  buttonText: { color: '#FFFFFF', fontSize: 18, fontWeight: 'bold' },
  linkText: { textAlign: 'center', marginTop: 25, color: '#718096', fontSize: 15 },
  linkBold: { color: '#3182CE', fontWeight: 'bold' },
  header: { padding: 20, backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderBottomColor: '#E2E8F0', paddingTop: Platform.OS === 'android' ? 40 : 20 },
  headerTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  headerTitle: { fontSize: 26, fontWeight: 'bold', color: '#1A365D' },
  logoutText: { color: '#E53E3E', fontWeight: 'bold', fontSize: 15 },
  headerSubtitle: { fontSize: 15, color: '#4A5568', marginTop: 4 },
  searchContainer: { padding: 15 },
  searchBar: { backgroundColor: '#FFFFFF', padding: 16, borderRadius: 15, borderWidth: 1, borderColor: '#CBD5E0', fontSize: 16 },
  listContent: { padding: 15 },
  bookCard: { backgroundColor: '#FFFFFF', borderRadius: 16, marginBottom: 18, flexDirection: 'row', padding: 12, elevation: 4 },
  bookImage: { width: 90, height: 135, borderRadius: 10 },
  bookInfo: { flex: 1, marginLeft: 18, justifyContent: 'center' },
  bookTitle: { fontSize: 18, fontWeight: 'bold', color: '#2D3748' },
  bookAuthor: { fontSize: 14, color: '#718096', marginTop: 6, marginBottom: 10 },
  badge: { backgroundColor: '#EBF8FF', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 6, alignSelf: 'flex-start' },
  badgeText: { color: '#3182CE', fontSize: 12, fontWeight: 'bold' },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 20 },
  loadingText: { marginTop: 10, color: '#4A5568' },
  errorText: { fontSize: 16, color: '#E53E3E', textAlign: 'center', marginBottom: 20 },
  retryButton: { backgroundColor: '#3182CE', paddingHorizontal: 20, paddingVertical: 12, borderRadius: 10 },
  retryButtonText: { color: '#FFFFFF', fontWeight: 'bold' },
  emptyText: { textAlign: 'center', color: '#718096', marginTop: 50, fontSize: 16 },
  modalContainer: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'flex-end' },
  modalContent: { backgroundColor: '#FFFFFF', borderTopLeftRadius: 30, borderTopRightRadius: 30, padding: 25, height: '85%' },
  closeButton: { alignSelf: 'flex-end', padding: 10 },
  closeButtonText: { fontSize: 28, color: '#A0AEC0' },
  modalImage: { width: 140, height: 210, borderRadius: 12, alignSelf: 'center', marginBottom: 25 },
  modalTitle: { fontSize: 24, fontWeight: 'bold', color: '#1A365D', textAlign: 'center', marginBottom: 10 },
  modalAuthor: { fontSize: 16, color: '#718096', textAlign: 'center', marginBottom: 25 },
  modalDescription: { fontSize: 16, color: '#4A5568', lineHeight: 26, textAlign: 'justify', marginBottom: 30 },
  readButton: { backgroundColor: '#3182CE', padding: 20, borderRadius: 15, alignItems: 'center', marginBottom: 30 },
  readButtonText: { color: '#FFFFFF', fontSize: 18, fontWeight: 'bold' }
});
